#ifndef __TERM_ACCSENSOR__
#define __TERM_ACCSENSOR__

#define TERM_SENSOR_X_MIN    1590
#define TERM_SENSOR_X_MAX    2450
#define TERM_SENSOR_X_RANGE  (TERM_SENSOR_X_MAX - TERM_SENSOR_X_MIN)
#define TERM_SENSOR_Y_MIN    3550
#define TERM_SENSOR_Y_MAX    3770
#define TERM_SENSOR_Y_RANGE  (TERM_SENSOR_Y_MAX - TERM_SENSOR_Y_MIN)

#endif